### ISSUE TITLE
Do not assume that the application will link against libwayland-client.so

### ISSUE THREAD

**Issue by edrickhong** [GPUOpen-Drivers/wsa#4]
My application and applications that use SDL do not directly link to libwayland-client.so
This will make wayland support impossible for such applications cos dlopen will fail

Pal::Linux::WaylandWindowSystem::LoadWaylandWsa () at /AMDVLK/vulkandriver/drivers/pal/src/core/os/lnx/wayland/waylandWindowSystem.cpp:146

(gdb) print (const s8*)dlerror()
$11 = (const s8 *) 0x32700e0 "/lib64/libamdgpu_wsa_wayland.so: undefined symbol: wl_callback_interface"

**Comment by edrickhong** [comment]
2
down vote
accepted

The POSIX spec for dlopen() says:

    Only a single copy of an executable object file shall be brought into the address space, even if dlopen() is invoked multiple times in reference to the executable object file, and even if different pathnames are used to reference the executable object file.

I think you might be able to get away with dlopening the library

**Comment by edrickhong** [comment]
I just confirmed that dlopen will reuse the addresses that have been previously mapped, so dlopening libwayland-client.so should work.

This is how I got around the includes' inline functions and interfaces:
[header file](https://github.com/edrickhong/Cu/blob/master/src/cu_std/linux/wayland_dyn.h)

wayland-client.h cannot be included. Instead, just add function pointers as needed.

**Comment by edrickhong** [comment]
I managed to patch it with the header above with a few changes and function pointer initialization. I am gonna try using it to present using it first before I consider it done. Should I make a pull request? And if so, I am using this header in my project own as well. What is the legal implications of this?

**Comment by hudeng** [comment]
This is a typo in cmake file, we already have a fix in our internal branch, and will port it here soon.
libwayland-client.so should be added as a dependency to libamdgpu_wsa_wayland.so, on your local, you can modify wsa/wayland/CMakeLists.txt to have a try :)
change 

**target_include_directories ( amdgpu_wsa_wayland PUBLIC ${WAYLAND_CLIENT_INCLUDE_DIRS} )
target_link_libraries ( amdgpu_wsa_wayland PUBLIC ${WAYLAND_CLIENT_LDFLAGS} )**

to

**target_include_directories ( amdgpu_wsa_wayland PUBLIC ${WAYLAND_INCLUDE_DIRS} )
target_link_libraries ( amdgpu_wsa_wayland PUBLIC ${WAYLAND_LDFLAGS} )**

**Comment by edrickhong** [comment]
Thanks. I'll make that change and give it a go tomorrow. I don't see why this wouldn't work either.
